apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: 0872/zookeeper:latest
        ports:
        - name: zookeeper
          containerPort: 49494
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
        - name: zookeeper-config-volume
          mountPath: /opt/zookeeper/conf/zoo.cfg
          subPath: zoo.cfg
      volumes:
      - name: zookeeper-config-volume
        configMap:
          name: zookeeper-config

