apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
  selector:
    app: zookeeper
