apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      name: webhook
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: 0872/alert-manager-webhook:latest
        ports:
        - name: alertmanager
          containerPort: 49494
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
        - name: alarm-mapping-config-volume
          mountPath: /etc/opt/ericsson/mapping.yml
          subPath: mapping.yml
      volumes:
      - name: alarm-mapping-config-volume
        configMap:
          name: alarm-mapping-config

