apiVersion: v1
kind: Service
metadata:
  name: alert-manager-webhook
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
spec:
  type: ClusterIP
  ports:
    - port: 49494
      targetPort: 49494
      name: alarm-handler-webhook
  selector:
    app: webhook
