kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m

      receiver: webhook

      routes:
        - receiver: webhook
          continue: true


    receivers:
    - name: webhook
      webhook_configs:
      - url: http://alert-manager-webhook.default.svc:49494/api/alertnotifications
