apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  annotations:
# the annotations here means we dont have to add a scrape job to the prometheus.yaml
#the annotatons are not working so i added as a scrape job and service is UP
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093

