apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  mapping.yml: |
    faultName: [['labels','alertname']]
    serviceName: [['labels','deployment'],  ['labels','statefulset'],  ['labels','daemonset']]
    createdAt: [] #Blank mapping returns current datetime
    expiration: [['endsAt']]
    faultyResource: [['labels','instance']]
    severity: [['labels','severity']]
    description: [['annotations','summary']]
    additional_information:
    namespace:  [['labels','namespace'], ['labels','kubernetes_namespace']]